FROM node:20-alpine

WORKDIR /app/services/websocket-server

COPY services/websocket-server/package*.json ./
RUN apk add --no-cache git && npm install -g prisma@6.0.0 && npm install

COPY services/websocket-server/tsconfig.json ./
COPY services/websocket-server/src ./src
COPY shared /app/shared

WORKDIR /app
RUN npx prisma generate --schema=./shared/prisma/schema.prisma
WORKDIR /app/services/websocket-server

RUN npm run build

EXPOSE 3001

CMD ["node", "dist/index.js"]
