FROM node:20-alpine

WORKDIR /app/services/discord-gateway

COPY services/discord-gateway/package*.json ./
RUN apk add --no-cache git && npm install

COPY services/discord-gateway/tsconfig.json ./
COPY services/discord-gateway/src ./src
COPY shared /app/shared

RUN npx prisma generate

RUN npm run build

CMD ["node", "dist/index.js"]
