FROM node:20-alpine

WORKDIR /app/services/websocket-server

COPY services/websocket-server/package*.json ./
RUN apk add --no-cache git && npm install

COPY services/websocket-server/tsconfig.json ./
COPY services/websocket-server/src ./src
COPY shared /app/shared

RUN npx prisma generate --schema=/app/shared/prisma/schema.prisma --output-dir=./node_modules/.prisma/client

RUN npm run build

EXPOSE 3001

CMD ["node", "dist/index.js"]
