FROM node:20-alpine

WORKDIR /app/services/worker

COPY services/worker/package*.json ./
RUN apk add --no-cache git && npm install && npx prisma generate

COPY services/worker/tsconfig.json ./
COPY services/worker/src ./src
COPY shared /app/shared

RUN npm run build

CMD ["node", "dist/index.js"]
